#!/bin/bash

VERILOG_COMPLIER=iverilog
VERILOG_RUNTIME=vvp
VERILOG_STANDARD=2012
TEMP_FILE_NAME=temp.v
PYTHON=python3

TB=$1

CWD=$(pwd)
TOP=$(echo ./tests/$(echo $TB)/top.v)

SOURCE_FILES=$(find designs/*)

TEMP_FILE_INCLUDES=$(for i in $SOURCE_FILES; do printf "\`include \"$i\"\n"; done)

printf "$TEMP_FILE_INCLUDES" > $TEMP_FILE_NAME
printf "\n\n" >> $TEMP_FILE_NAME
cat $TOP >> $TEMP_FILE_NAME
mkdir -p ./simulations/$TB

$VERILOG_COMPLIER -g2005 -ldesigns -d synth2 -S -tsizer -o ./simulations/$TB/sizer.txt -s top $TEMP_FILE_NAME
rm $TEMP_FILE_NAME